/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125DashboardRouteImport } from './routes/{-$locale}/dashboard'
import { Route as Char123LocaleChar125AuthVerifyRouteImport } from './routes/{-$locale}/auth/verify'
import { Route as Char123LocaleChar125AuthSignupRouteImport } from './routes/{-$locale}/auth/signup'
import { Route as Char123LocaleChar125AuthSigninRouteImport } from './routes/{-$locale}/auth/signin'
import { Route as Char123LocaleChar125AuthResendVerificationRouteImport } from './routes/{-$locale}/auth/resend-verification'

const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/{-$locale}/',
    path: '/{-$locale}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125DashboardRoute =
  Char123LocaleChar125DashboardRouteImport.update({
    id: '/{-$locale}/dashboard',
    path: '/{-$locale}/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125AuthVerifyRoute =
  Char123LocaleChar125AuthVerifyRouteImport.update({
    id: '/{-$locale}/auth/verify',
    path: '/{-$locale}/auth/verify',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125AuthSignupRoute =
  Char123LocaleChar125AuthSignupRouteImport.update({
    id: '/{-$locale}/auth/signup',
    path: '/{-$locale}/auth/signup',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125AuthSigninRoute =
  Char123LocaleChar125AuthSigninRouteImport.update({
    id: '/{-$locale}/auth/signin',
    path: '/{-$locale}/auth/signin',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125AuthResendVerificationRoute =
  Char123LocaleChar125AuthResendVerificationRouteImport.update({
    id: '/{-$locale}/auth/resend-verification',
    path: '/{-$locale}/auth/resend-verification',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}/dashboard': typeof Char123LocaleChar125DashboardRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/auth/resend-verification': typeof Char123LocaleChar125AuthResendVerificationRoute
  '/{-$locale}/auth/signin': typeof Char123LocaleChar125AuthSigninRoute
  '/{-$locale}/auth/signup': typeof Char123LocaleChar125AuthSignupRoute
  '/{-$locale}/auth/verify': typeof Char123LocaleChar125AuthVerifyRoute
}
export interface FileRoutesByTo {
  '/{-$locale}/dashboard': typeof Char123LocaleChar125DashboardRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/auth/resend-verification': typeof Char123LocaleChar125AuthResendVerificationRoute
  '/{-$locale}/auth/signin': typeof Char123LocaleChar125AuthSigninRoute
  '/{-$locale}/auth/signup': typeof Char123LocaleChar125AuthSignupRoute
  '/{-$locale}/auth/verify': typeof Char123LocaleChar125AuthVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}/dashboard': typeof Char123LocaleChar125DashboardRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/auth/resend-verification': typeof Char123LocaleChar125AuthResendVerificationRoute
  '/{-$locale}/auth/signin': typeof Char123LocaleChar125AuthSigninRoute
  '/{-$locale}/auth/signup': typeof Char123LocaleChar125AuthSignupRoute
  '/{-$locale}/auth/verify': typeof Char123LocaleChar125AuthVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}/dashboard'
    | '/{-$locale}/'
    | '/{-$locale}/auth/resend-verification'
    | '/{-$locale}/auth/signin'
    | '/{-$locale}/auth/signup'
    | '/{-$locale}/auth/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}/dashboard'
    | '/{-$locale}'
    | '/{-$locale}/auth/resend-verification'
    | '/{-$locale}/auth/signin'
    | '/{-$locale}/auth/signup'
    | '/{-$locale}/auth/verify'
  id:
    | '__root__'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/'
    | '/{-$locale}/auth/resend-verification'
    | '/{-$locale}/auth/signin'
    | '/{-$locale}/auth/signup'
    | '/{-$locale}/auth/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125DashboardRoute: typeof Char123LocaleChar125DashboardRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125AuthResendVerificationRoute: typeof Char123LocaleChar125AuthResendVerificationRoute
  Char123LocaleChar125AuthSigninRoute: typeof Char123LocaleChar125AuthSigninRoute
  Char123LocaleChar125AuthSignupRoute: typeof Char123LocaleChar125AuthSignupRoute
  Char123LocaleChar125AuthVerifyRoute: typeof Char123LocaleChar125AuthVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/{-$locale}'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/dashboard': {
      id: '/{-$locale}/dashboard'
      path: '/{-$locale}/dashboard'
      fullPath: '/{-$locale}/dashboard'
      preLoaderRoute: typeof Char123LocaleChar125DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/auth/verify': {
      id: '/{-$locale}/auth/verify'
      path: '/{-$locale}/auth/verify'
      fullPath: '/{-$locale}/auth/verify'
      preLoaderRoute: typeof Char123LocaleChar125AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/auth/signup': {
      id: '/{-$locale}/auth/signup'
      path: '/{-$locale}/auth/signup'
      fullPath: '/{-$locale}/auth/signup'
      preLoaderRoute: typeof Char123LocaleChar125AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/auth/signin': {
      id: '/{-$locale}/auth/signin'
      path: '/{-$locale}/auth/signin'
      fullPath: '/{-$locale}/auth/signin'
      preLoaderRoute: typeof Char123LocaleChar125AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/auth/resend-verification': {
      id: '/{-$locale}/auth/resend-verification'
      path: '/{-$locale}/auth/resend-verification'
      fullPath: '/{-$locale}/auth/resend-verification'
      preLoaderRoute: typeof Char123LocaleChar125AuthResendVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125DashboardRoute: Char123LocaleChar125DashboardRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  Char123LocaleChar125AuthResendVerificationRoute:
    Char123LocaleChar125AuthResendVerificationRoute,
  Char123LocaleChar125AuthSigninRoute: Char123LocaleChar125AuthSigninRoute,
  Char123LocaleChar125AuthSignupRoute: Char123LocaleChar125AuthSignupRoute,
  Char123LocaleChar125AuthVerifyRoute: Char123LocaleChar125AuthVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
