/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicTermsOfServiceRouteImport } from './routes/_public/terms-of-service'
import { Route as PublicPrivacyPolicyRouteImport } from './routes/_public/privacy-policy'
import { Route as PublicDocsRouteImport } from './routes/_public/docs'
import { Route as PublicBlogRouteImport } from './routes/_public/blog'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as PublicAuthSigninRouteImport } from './routes/_public/auth/signin'
import { Route as PublicAuthResendVerificationRouteImport } from './routes/_public/auth/resend-verification'
import { Route as PublicAuthSignupIndexRouteImport } from './routes/_public/auth/signup/index'
import { Route as PublicAuthResetPasswordIndexRouteImport } from './routes/_public/auth/reset-password/index'
import { Route as PublicAuthSignupTokenRouteImport } from './routes/_public/auth/signup/$token'
import { Route as PublicAuthResetPasswordTokenRouteImport } from './routes/_public/auth/reset-password/$token'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTermsOfServiceRoute = PublicTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyPolicyRoute = PublicPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDocsRoute = PublicDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogRoute = PublicBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRoute,
} as any)
const PublicAuthSigninRoute = PublicAuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthResendVerificationRoute =
  PublicAuthResendVerificationRouteImport.update({
    id: '/auth/resend-verification',
    path: '/auth/resend-verification',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicAuthSignupIndexRoute = PublicAuthSignupIndexRouteImport.update({
  id: '/auth/signup/',
  path: '/auth/signup/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthResetPasswordIndexRoute =
  PublicAuthResetPasswordIndexRouteImport.update({
    id: '/auth/reset-password/',
    path: '/auth/reset-password/',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicAuthSignupTokenRoute = PublicAuthSignupTokenRouteImport.update({
  id: '/auth/signup/$token',
  path: '/auth/signup/$token',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthResetPasswordTokenRoute =
  PublicAuthResetPasswordTokenRouteImport.update({
    id: '/auth/reset-password/$token',
    path: '/auth/reset-password/$token',
    getParentRoute: () => PublicRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/blog': typeof PublicBlogRoute
  '/docs': typeof PublicDocsRoute
  '/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/terms-of-service': typeof PublicTermsOfServiceRoute
  '/auth/resend-verification': typeof PublicAuthResendVerificationRoute
  '/auth/signin': typeof PublicAuthSigninRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
  '/auth/reset-password/$token': typeof PublicAuthResetPasswordTokenRoute
  '/auth/signup/$token': typeof PublicAuthSignupTokenRoute
  '/auth/reset-password/': typeof PublicAuthResetPasswordIndexRoute
  '/auth/signup/': typeof PublicAuthSignupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/blog': typeof PublicBlogRoute
  '/docs': typeof PublicDocsRoute
  '/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/terms-of-service': typeof PublicTermsOfServiceRoute
  '/auth/resend-verification': typeof PublicAuthResendVerificationRoute
  '/auth/signin': typeof PublicAuthSigninRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/auth/reset-password/$token': typeof PublicAuthResetPasswordTokenRoute
  '/auth/signup/$token': typeof PublicAuthSignupTokenRoute
  '/auth/reset-password': typeof PublicAuthResetPasswordIndexRoute
  '/auth/signup': typeof PublicAuthSignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/blog': typeof PublicBlogRoute
  '/_public/docs': typeof PublicDocsRoute
  '/_public/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/_public/terms-of-service': typeof PublicTermsOfServiceRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/auth/resend-verification': typeof PublicAuthResendVerificationRoute
  '/_public/auth/signin': typeof PublicAuthSigninRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_public/auth/reset-password/$token': typeof PublicAuthResetPasswordTokenRoute
  '/_public/auth/signup/$token': typeof PublicAuthSignupTokenRoute
  '/_public/auth/reset-password/': typeof PublicAuthResetPasswordIndexRoute
  '/_public/auth/signup/': typeof PublicAuthSignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/docs'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/auth/resend-verification'
    | '/auth/signin'
    | '/dashboard/'
    | '/auth/reset-password/$token'
    | '/auth/signup/$token'
    | '/auth/reset-password/'
    | '/auth/signup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/docs'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/auth/resend-verification'
    | '/auth/signin'
    | '/dashboard'
    | '/auth/reset-password/$token'
    | '/auth/signup/$token'
    | '/auth/reset-password'
    | '/auth/signup'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/_public/blog'
    | '/_public/docs'
    | '/_public/privacy-policy'
    | '/_public/terms-of-service'
    | '/_public/'
    | '/_public/auth/resend-verification'
    | '/_public/auth/signin'
    | '/_protected/dashboard/'
    | '/_public/auth/reset-password/$token'
    | '/_public/auth/signup/$token'
    | '/_public/auth/reset-password/'
    | '/_public/auth/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/terms-of-service': {
      id: '/_public/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof PublicTermsOfServiceRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy-policy': {
      id: '/_public/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PublicPrivacyPolicyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/docs': {
      id: '/_public/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof PublicDocsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog': {
      id: '/_public/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof PublicBlogRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_public/auth/signin': {
      id: '/_public/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof PublicAuthSigninRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/resend-verification': {
      id: '/_public/auth/resend-verification'
      path: '/auth/resend-verification'
      fullPath: '/auth/resend-verification'
      preLoaderRoute: typeof PublicAuthResendVerificationRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/signup/': {
      id: '/_public/auth/signup/'
      path: '/auth/signup'
      fullPath: '/auth/signup/'
      preLoaderRoute: typeof PublicAuthSignupIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/reset-password/': {
      id: '/_public/auth/reset-password/'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password/'
      preLoaderRoute: typeof PublicAuthResetPasswordIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/signup/$token': {
      id: '/_public/auth/signup/$token'
      path: '/auth/signup/$token'
      fullPath: '/auth/signup/$token'
      preLoaderRoute: typeof PublicAuthSignupTokenRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/reset-password/$token': {
      id: '/_public/auth/reset-password/$token'
      path: '/auth/reset-password/$token'
      fullPath: '/auth/reset-password/$token'
      preLoaderRoute: typeof PublicAuthResetPasswordTokenRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicBlogRoute: typeof PublicBlogRoute
  PublicDocsRoute: typeof PublicDocsRoute
  PublicPrivacyPolicyRoute: typeof PublicPrivacyPolicyRoute
  PublicTermsOfServiceRoute: typeof PublicTermsOfServiceRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicAuthResendVerificationRoute: typeof PublicAuthResendVerificationRoute
  PublicAuthSigninRoute: typeof PublicAuthSigninRoute
  PublicAuthResetPasswordTokenRoute: typeof PublicAuthResetPasswordTokenRoute
  PublicAuthSignupTokenRoute: typeof PublicAuthSignupTokenRoute
  PublicAuthResetPasswordIndexRoute: typeof PublicAuthResetPasswordIndexRoute
  PublicAuthSignupIndexRoute: typeof PublicAuthSignupIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicBlogRoute: PublicBlogRoute,
  PublicDocsRoute: PublicDocsRoute,
  PublicPrivacyPolicyRoute: PublicPrivacyPolicyRoute,
  PublicTermsOfServiceRoute: PublicTermsOfServiceRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicAuthResendVerificationRoute: PublicAuthResendVerificationRoute,
  PublicAuthSigninRoute: PublicAuthSigninRoute,
  PublicAuthResetPasswordTokenRoute: PublicAuthResetPasswordTokenRoute,
  PublicAuthSignupTokenRoute: PublicAuthSignupTokenRoute,
  PublicAuthResetPasswordIndexRoute: PublicAuthResetPasswordIndexRoute,
  PublicAuthSignupIndexRoute: PublicAuthSignupIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
